# Generated by Django 5.0.6 on 2024-06-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="files.folder",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="files.folder",
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="files.folder"
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
    ]
