# Generated by Django 5.0.6 on 2024-06-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_file_owner_alter_folder_owner_alter_share_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Share",
        ),
    ]
